version: 2

# all images have same environment variables
environment: &environment
  TERM: xterm
  npm_config_loglevel: warn
  # even when running as non-root user
  # need to set unsafe perm to be able to do `npm postinstall`
  npm_config_unsafe-perm: true

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    # be explicit about the Docker image we use
    - image: cypress/base:8
      <<: *environment

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      - run: npm ci
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
      - run: npm run lint

  ## Docker image without XVFB - Cypress should NOT work
  test-bare:
    <<: *defaults
    # override just the docker image
    docker:
      - image: node:6
        <<: *environment
    steps:
      - checkout
      - run: npm install
      - run: npm install @cypress/commit-message-install
      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      - run: $(npm bin)/run-if npm run test-bare
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "$CIRCLE_STAGE on CircleCI"

  ## Docker image with XVFB - Cypress should NOT work
  test-xvfb:
    <<: *defaults
    docker:
      - image: cypressinternal/xvfb
        <<: *environment
    steps:
      - checkout
      - run: npm install
      - run: npm install @cypress/commit-message-install
      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      - run: $(npm bin)/run-if npm run test-xvfb
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "$CIRCLE_STAGE on CircleCI"

  ## Docker image with all dependencies - Cypress should work
  test-full:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm install @cypress/commit-message-install
      - run: ls node_modules/.bin
      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      - run: $(npm bin)/run-if npm run verify
      - run: $(npm bin)/run-if npm run test-full
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "$CIRCLE_STAGE on CircleCI"

  # Good image - except the user set DISPLAY to some wrong value
  # our "cypress verify" and "cypress run"  should retry automatically and work
  test-bad-display-variable:
    <<: *defaults
    steps:
      - run: echo "TERM is $TERM"
      - checkout
      - run: npm install
      - run: npm install @cypress/commit-message-install
      - run: ls node_modules/.bin
      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      # do not verify Cypress binary - it will be done from the test
      - run: $(npm bin)/run-if npm run test-display-retry
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "$CIRCLE_STAGE on CircleCI"

  test-full-node8.15.1:
    <<: *defaults
    docker:
      - image: cypress/base:8.15.1
        <<: *environment
    steps:
      - checkout
      - run: npm install
      - run: npm install @cypress/commit-message-install
      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      - run: $(npm bin)/run-if npm run verify
      - run: $(npm bin)/run-if npm run test-full
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "$CIRCLE_STAGE on CircleCI"

  test-full-node8.9.3:
    <<: *defaults
    docker:
      # use a newer Docker image with better NPM version to avoid
      # installation problems
      - image: cypress/base:8.9.3-npm-6.10.1
        <<: *environment
    steps:
      - checkout
      - run: npm install
      - run: npm install @cypress/commit-message-install
      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      - run: $(npm bin)/run-if npm run verify
      - run: $(npm bin)/run-if npm run test-full
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "$CIRCLE_STAGE on CircleCI"

  test-full-node10.15.3:
    <<: *defaults
    docker:
      - image: cypress/base:10.15.3
        <<: *environment
    steps:
      - checkout
      - run: npm install
      - run: npm install @cypress/commit-message-install
      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      - run: $(npm bin)/run-if npm run verify
      - run: $(npm bin)/run-if npm run test-full
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "$CIRCLE_STAGE on CircleCI"

  ## Centos7 image - Cypress should work
  test-centos7:
    <<: *defaults
    # override just the docker image
    docker:
      - image: cypress/base:centos7
        <<: *environment
    steps:
      - checkout
      - run: npm install
      - run: npm install @cypress/commit-message-install
      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      - run: $(npm bin)/run-if npm run verify
      - run: $(npm bin)/run-if npm run test-full
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "$CIRCLE_STAGE on CircleCI"

  ## Ubuntu 16.04 image - Cypress should work
  test-ubuntu16:
    <<: *defaults
    # override just the docker image
    docker:
      - image: cypress/base:ubuntu16
        <<: *environment
    steps:
      - run: git --version
      - checkout
      - run: npm install
      - run: npm install @cypress/commit-message-install
      - run: $(npm bin)/commit-message-install --else "npm install cypress"
      - run: $(npm bin)/run-if npm run verify
      - run: $(npm bin)/run-if npm run test-full
      - run:
          when: on_fail
          name: Set status check
          command: $(npm bin)/set-status --state failure --description "$CIRCLE_STAGE on CircleCI"

  after-tests:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm install @cypress/commit-message-install
      - run:
          when: on_success
          name: Set status check
          command: $(npm bin)/set-status --state success --description "on CircleCI"

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test-full
      - test-full-node8.9.3
      - test-full-node8.15.1
      - test-full-node10.15.3
      - test-bare
      - test-xvfb
      - test-ubuntu16
      - test-bad-display-variable
      # disabling this test - has been failing forever
      # https://github.com/cypress-io/cypress-test-ci-environments/issues/7
      # - test-centos7

      - after-tests:
          requires:
            - lint
            - test-full
            - test-full-node8.9.3
            - test-full-node8.15.1
            - test-full-node10.15.3
            - test-bare
            - test-xvfb
            - test-ubuntu16
            - test-bad-display-variable
