version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cypress/base
      environment:
        term: XTERM
        npm_config_loglevel: warn
        # even when running as non-root user
        # need to set unsafe perm to be able to do `npm postinstall`
        npm_config_unsafe-perm: true

jobs:
  ## Docker image without XVFB - Cypress should NOT work
  test-bare:
    <<: *defaults
    docker:
      - image: node:6
        environment:
          term: XTERM
          npm_config_loglevel: warn
          # even when running as non-root user
          # need to set unsafe perm to be able to do `npm postinstall`
          npm_config_unsafe-perm: true
    steps:
      - checkout
      - run: npm install
      - run: $(npm bin)/commit-message-install
      - run: npm run test-bare

  ## Docker image with XVFB - Cypress should NOT work
  test-xvfb:
    <<: *defaults
    docker:
      - image: cypress/internal:xvfb
        environment:
          term: XTERM
          npm_config_loglevel: warn
          # even when running as non-root user
          # need to set unsafe perm to be able to do `npm postinstall`
          npm_config_unsafe-perm: true
    steps:
      - checkout
      - run: npm install
      - run: $(npm bin)/commit-message-install
      - run: npm run test-xvfb

  ## Docker image with all dependencies - Cypress should work
  test-full:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: $(npm bin)/commit-message-install
      - run: npm run test-full

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-full
      - test-bare
      - test-xvfb
