version: 2

# all images have same environment variables
environment: &environment
  term: XTERM
  npm_config_loglevel: warn
  # even when running as non-root user
  # need to set unsafe perm to be able to do `npm postinstall`
  npm_config_unsafe-perm: true

defaults: &defaults
  parallelism: 1
  working_directory: ~/app
  docker:
    - image: cypress/base
  environment: *environment

jobs:
  ## Docker image without XVFB - Cypress should NOT work
  test-bare:
    <<: *defaults
    # override just the docker image
    docker:
      - image: node:6
    environment: *environment
    steps:
      - checkout
      - run: npm install
      # hmm, now that we do not include Cypress as a dependency
      # have to install it
      - run: npm install cypress
      - run: $(npm bin)/commit-message-install
      - run: $(npm bin)/run-if npm run test-bare

  ## Docker image with XVFB - Cypress should NOT work
  test-xvfb:
    <<: *defaults
    docker:
      - image: cypressinternal/xvfb
    environment: *environment
    steps:
      - checkout
      - run: npm install
      - run: npm install cypress
      - run: $(npm bin)/commit-message-install
      - run: $(npm bin)/run-if npm run test-xvfb

  ## Docker image with all dependencies - Cypress should work
  test-full:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm install cypress
      - run: $(npm bin)/commit-message-install
      - run: $(npm bin)/run-if npm run verify
      - run: $(npm bin)/run-if npm run test-full

  ## Centos7 image - Cypress should work
  test-centos7:
    <<: *defaults
    # override just the docker image
    docker:
      - image: cypress/base:centos7
    environment: *environment
    steps:
      - checkout
      - run: npm install
      - run: npm install cypress
      - run: $(npm bin)/commit-message-install
      - run: $(npm bin)/run-if npm run verify
      - run: $(npm bin)/run-if npm run test-full

  ## Ubuntu 16.04 image - Cypress should work
  test-ubuntu16:
    <<: *defaults
    # override just the docker image
    docker:
      - image: cypress/base:ubuntu16
    environment: *environment
    steps:
      - run: git --version
      - checkout
      - run: npm install
      - run: npm install cypress
      - run: $(npm bin)/commit-message-install
      - run: $(npm bin)/run-if npm run verify
      - run: $(npm bin)/run-if npm run test-full

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-full
      - test-bare
      - test-xvfb
      - test-centos7
      - test-ubuntu16
